<!--
Codes Generated By VForm:
https://www.vform666.com
-->

<template>
  <el-form :model="formData" ref="vForm" :rules="rules" label-position="left" label-width="80px" size="medium"
           @submit.native.prevent>
    <el-form-item label="file-upload" prop="fileupload58108">
      <el-upload :file-list="fileupload58108FileList" :headers="fileupload58108UploadHeaders"
                 :data="fileupload58108UploadData" list-type="picture-card" show-file-list :limit="3"> <template
        #default><i class="el-icon-plus"></i></template></el-upload>
    </el-form-item>
    <div class="static-content-item">
<!--      <div v-html="<b>html text</b>"></div>-->
      <div> 123 </div>
    </div>
    <el-form-item label="rate" prop="rate98623">
      <el-rate v-model="formData.rate98623"></el-rate>
    </el-form-item>
    <el-form-item label="switch" prop="switch59878">
      <el-switch v-model="formData.switch59878"></el-switch>
    </el-form-item>
    <el-form-item label="rich-editor" prop="richeditor9346">
      <vue-editor v-model="formData.richeditor9346"></vue-editor>
    </el-form-item>
  </el-form>

</template>

<script>
  export default {
    name: 'help',
    components: {},
    props: {},
    data() {
      return {
        formData: {
          fileupload58108: null,
          rate98623: 0,
          switch59878: false,
          richeditor9346: null,
        },
        rules: {},
        fileupload58108FileList: [],
        fileupload58108UploadHeaders: {},
        fileupload58108UploadData: {},
      }
    },
    computed: {},
    watch: {},
    created() {},
    mounted() {},
    methods: {
      submitForm() {
        this.$refs['vForm'].validate(valid => {
          if (!valid) return
          //TODO: 提交表单
        })
      },
      resetForm() {
        this.$refs['vForm'].resetFields()
      }
    }
  }

</script>

<style lang="scss">
  .el-input-number.full-width-input,
  .el-cascader.full-width-input {
    width: 100% !important;
  }

  .el-form-item--medium {
    .el-radio {
      line-height: 36px !important;
    }

    .el-rate {
      margin-top: 8px;
    }
  }

  .el-form-item--small {
    .el-radio {
      line-height: 32px !important;
    }

    .el-rate {
      margin-top: 6px;
    }
  }

  .el-form-item--mini {
    .el-radio {
      line-height: 28px !important;
    }

    .el-rate {
      margin-top: 4px;
    }
  }

  .clear-fix:before,
  .clear-fix:after {
    display: table;
    content: "";
  }

  .clear-fix:after {
    clear: both;
  }

  .float-right {
    float: right;
  }

</style>

<style lang="scss" scoped>
  div.table-container {
    table.table-layout {
      width: 100%;
      table-layout: fixed;
      border-collapse: collapse;

      td.table-cell {
        display: table-cell;
        height: 36px;
        border: 1px solid #e1e2e3;
      }
    }
  }

  div.tab-container {}

  .label-left-align ::v-deep .el-form-item__label {
    text-align: left;
  }

  .label-center-align ::v-deep .el-form-item__label {
    text-align: center;
  }

  .label-right-align ::v-deep .el-form-item__label {
    text-align: right;
  }

  .custom-label {}

  .static-content-item {
    min-height: 20px;
    display: flex;
    align-items: center;

    ::v-deep .el-divider--horizontal {
      margin: 0;
    }
  }

</style>
